# Generated by Django 6.0 on 2026-02-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('face_detected_count', models.PositiveIntegerField(default=0)),
                ('no_face_count', models.PositiveIntegerField(default=0)),
                ('multiple_faces_count', models.PositiveIntegerField(default=0)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('looking_away_count', models.PositiveIntegerField(default=0)),
                ('exam_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exams.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='MalpracticeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('looking_away', 'Looking Away from Screen'), ('tab_switch', 'Tab Switched'), ('copy_paste', 'Copy/Paste Attempted'), ('fullscreen_exit', 'Fullscreen Exited')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='malpractice.examsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
