# Generated by Django 4.2.28 on 2026-02-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='last_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='live_snapshots/'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='phone_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='malpracticeevent',
            name='event_type',
            field=models.CharField(choices=[('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('looking_away', 'Looking Away from Screen'), ('tab_switch', 'Tab Switched'), ('copy_paste', 'Copy/Paste Attempted'), ('fullscreen_exit', 'Fullscreen Exited'), ('phone_usage', 'Phone/Mobile Detected')], max_length=50),
        ),
    ]
