# Generated by Django 4.2.28 on 2026-02-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteToken',
        ),
    ]
