# Generated by Django 4.2.28 on 2026-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0002_add_snapshot_and_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpracticeevent',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='malpractice/'),
        ),
    ]
